workflows:
  native-android:
    name: Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    cache:
      cache_paths:
        - ~/.gradle/caches
        - $HOME/.gradle/caches	
    scripts:
      - name: View Machine Configuration
        script: |
          echo "Machine Configuration:"
          echo "----------------------"
          echo "CPU Info:"
          sysctl -n machdep.cpu.brand_string
          echo ""
          echo "Memory Info:"
          free -h
          echo ""
          echo "Disk Space:"
          df -h
          echo ""
          echo "Java Version:"
          java -version
          echo ""
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Print Java version
        script: |
          java -version
      - name: Grant execute permissions to gradlew
        script: |
          chmod +x gradlew

      - name: Build Android
        script: |
          # Build your Android project
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - 1552952669@qq.com
        
        notify:
          success: true
          failure: false
